root: true
env:
    es2021: true
    browser: true
    commonjs: true
    es6: true
    node: true
extends:
    - standard-with-typescript
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
    - plugin:@typescript-eslint/strict
    - plugin:@typescript-eslint/all
    - eslint:recommended
plugins:
    - "@typescript-eslint"
overrides:
    - files:
          - "*.ts"
          - "*.mts"
          - "*.cts"
      rules:
          "@typescript-eslint/explicit-module-boundary-types": error
          "@typescript-eslint/explicit-function-return-type": error
parser: "@typescript-eslint/parser"
ignorePatterns:
    - "vite.config.ts"
    - "reset.d.ts"
    - "*.tsx"
    - "*.js"
parserOptions:
    project:
        - "./tsconfig.json"
    ecmaVersion: latest
    sourceType: module
    typeAware: true
rules:
    linebreak-style: off
    indent: off
    "@typescript-eslint/indent": off
    semi: off
    "@typescript-eslint/semi": off
    "@typescript-eslint/quotes":
        - error
        - backtick

    "@typescript-eslint/member-delimiter-style": off
    #        - error
    #        -   multiline:
    #                delimiter: comma
    #                requireLast: false
    #            singleline:
    #                delimiter: comma
    #                requireLast: false
    #            overrides:
    #                interface:
    #                    multiline:
    #                        delimiter: none

    "no-unused-vars": off
    "@typescript-eslint/no-unused-vars": off
    "@typescript-eslint/no-type-alias": off
    "@typescript-eslint/no-magic-numbers": off
    "@typescript-eslint/space-before-function-paren": off
    "@typescript-eslint/prefer-readonly-parameter-types": off
    "@typescript-eslint/array-type":
        - error
        - default: generic
          readonly: generic
    "no-tabs": error

globals: {}
